### ISSUE TITLE
ngcc error with Angular 9.0.0-rc.4

### ISSUE THREAD

**Issue by vecernik** [swimlane/ngx-charts#1311]
When upgraded angular from 9.0.0-rc.3 to 9.0.0-rc.4, ngcc fails with following error:
```
$ ngcc --properties es2015 browser module main --first-only --create-ivy-entry-point
Compiling @swimlane/ngx-charts : module as esm5
Error: Error on worker #5: Error: Failed to compile entry-point @swimlane/ngx-charts due to compilation errors:
node_modules/@angular/common/common.d.ts(115,22): error TS-996002: Appears in the NgModule.imports of TooltipModule, but could not be resolved to an NgModule class
node_modules/@angular/common/common.d.ts(115,22): error TS-996002: Appears in the NgModule.imports of AxesModule, but could not be resolved to an NgModule class
node_modules/@angular/common/common.d.ts(115,22): error TS-996002: Appears in the NgModule.imports of ChartCommonModule, but could not be resolved to an NgModule class
node_modules/@swimlane/ngx-charts/release/esm.js(2832,5): error TS-996002: Appears in the NgModule.imports of ChartCommonModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(1062,5): error TS-996002: Appears in the NgModule.imports of ChartCommonModule, but itself has errors
node_modules/@angular/common/common.d.ts(115,22): error TS-996003: Appears in the NgModule.exports of ChartCommonModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class
node_modules/@swimlane/ngx-charts/release/esm.js(2832,5): error TS-996003: Appears in the NgModule.exports of ChartCommonModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(1062,5): error TS-996003: Appears in the NgModule.exports of ChartCommonModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996002: Appears in the NgModule.imports of AreaChartModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996002: Appears in the NgModule.imports of BarChartModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996002: Appears in the NgModule.imports of BubbleChartModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996002: Appears in the NgModule.imports of ForceDirectedGraphModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996002: Appears in the NgModule.imports of HeatMapModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996002: Appears in the NgModule.imports of LineChartModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996002: Appears in the NgModule.imports of PieChartModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996002: Appears in the NgModule.imports of PolarChartModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(13531,5): error TS-996002: Appears in the NgModule.imports of PolarChartModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(11717,5): error TS-996002: Appears in the NgModule.imports of PolarChartModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996002: Appears in the NgModule.imports of NumberCardModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996002: Appears in the NgModule.imports of TreeMapModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996002: Appears in the NgModule.imports of GaugeModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(13531,5): error TS-996002: Appears in the NgModule.imports of GaugeModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(9549,5): error TS-996002: Appears in the NgModule.imports of GaugeModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(4282,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(5816,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(9549,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(10196,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(10412,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(11000,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(11717,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(13560,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(13974,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(13531,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(14329,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors
node_modules/@swimlane/ngx-charts/release/esm.js(15029,5): error TS-996003: Appears in the NgModule.exports of NgxChartsModule, but itself has errors

    at ClusterWorker.compile (/charts-project/node_modules/@angular/compiler-cli/ngcc/src/main.js:170:27)
    at Worker.<anonymous> (/charts-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:41:42)
    at Worker.emit (events.js:210:5)
    at process.<anonymous> (internal/cluster/worker.js:34:12)
    at process.emit (events.js:210:5)
    at emit (internal/child_process.js:878:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
    at ClusterMaster.onWorkerMessage (/charts-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:158:27)
    at /charts-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:46:95
    at ClusterMaster.<anonymous> (/charts-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:238:57)
    at step (/charts-project/node_modules/tslib/tslib.js:136:27)
    at Object.next (/charts-project/node_modules/tslib/tslib.js:117:57)
    at /charts-project/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/charts-project/node_modules/tslib/tslib.js:106:16)
    at EventEmitter.<anonymous> (/charts-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:232:32)
    at EventEmitter.emit (events.js:210:5)
```

**Comment by marjan-georgiev** [comment]
Hi there, please refer to this comment: https://github.com/swimlane/ngx-charts/issues/1294#issuecomment-560380598

Closing this one.
