### ISSUE TITLE
heatmap does not work due to this.data being undefined

### ISSUE THREAD

**Issue by ansisatteka** [swimlane/ngx-charts#1455]
**Describe the bug**
Heatmap does not work with ngx-charts 14.0.0 (did not try other versions).

core.js:6237 ERROR TypeError: Cannot read property 'map' of undefined
    at HeatCellSeriesComponent.getCells (swimlane-ngx-charts.js:11259)
    at HeatCellSeriesComponent.update (swimlane-ngx-charts.js:11255)
    at HeatCellSeriesComponent.ngOnChanges (swimlane-ngx-charts.js:11252)
    at HeatCellSeriesComponent.wrapOnChangesHook_inPreviousChangesStorage (core.js:27137)
    at callHook (core.js:4739)
    at callHooks (core.js:4699)
    at executeInitAndCheckHooks (core.js:4639)
    at refreshView (core.js:11963)
    at refreshComponent (core.js:13410)
    at refreshChildComponents (core.js:11666)

**To Reproduce**

`export class HeatmapComponent implements OnInit {
  data: any[] = [
    {
      "name": "Germany",
      "series": [
        {
          "name": "2010",
          "value": 7300000
        },
        {
          "name": "2011",
          "value": 8940000
        }
      ]
    },

    {
      "name": "USA",
      "series": [
        {
          "name": "2010",
          "value": 7870000
        },
        {
          "name": "2011",
          "value": 8270000
        }
      ]
    }
  ]
`
`
<ngx-charts-heat-map
  [view]="view"
  [scheme]="colorScheme"
  [legend]="legend"
  [showXAxisLabel]="showXAxisLabel"
  [showYAxisLabel]="showYAxisLabel"
  [xAxis]="xAxis"
  [yAxis]="yAxis"
  [xAxisLabel]="xAxisLabel"
  [yAxisLabel]="yAxisLabel"
  [results]="data"
  (select)="onSelect($event)"
  (activate)="onActivate($event)"
  (deactivate)="onDeactivate($event)">
</ngx-charts-heat-map>`

**Expected behavior**
Should render something on screen.

**Screenshots**

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-charts version**

14.0.0

**Additional context**
