### ISSUE TITLE
`node.transition()` is not a function

### ISSUE THREAD

**Issue by JosephSKh** [swimlane/ngx-charts#377]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here
```

**Current behavior**
When building ngx-charts with D3 V4 it crashes and gives `node.transition()` is not a function this happens in the bar and pie component,, not sure if it happens in any else

**Expected behavior**
building smoothly

**Reproduction of the problem**
building it with D3 V4
ngx-charts v: 4.4.0
d3 v: 4.4.8

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** 4.4.0

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Can you check if installing d3 v 4.2.2 locally fixes this? It might be the d3 version, and we may need to update the library  to be compatible with the latest d3.

**Comment by JosephSKh** [comment]
@marjan-georgiev it works well with D3@4.2.2

**Comment by marjan-georgiev** [comment]
Ok, we'll update d3 in the next major version, as this would be a breaking change. Thanks for checking!
